# -*- coding: utf-8 -*-

cyrillic_dict = {
    u'А': unichr(ord('A')),
    u'Б': unichr(160),
    u'В': unichr(ord('B')),
    u'Г': unichr(161),
    u'Д': unichr(224),
    u'Е': unichr(ord('E')),
    u'Ё': unichr(162),
    u'Ж': unichr(163),
    u'З': unichr(164),
    u'И': unichr(165),
    u'Й': unichr(166),
    u'К': unichr(ord('K')),
    u'Л': unichr(167),
    u'М': unichr(ord('M')),
    u'Н': unichr(ord('H')),
    u'О': unichr(ord('O')),
    u'П': unichr(168),
    u'Р': unichr(ord('P')),
    u'С': unichr(ord('C')),
    u'Т': unichr(ord('T')),
    u'У': unichr(169),
    u'Ф': unichr(170),
    u'Х': unichr(ord('X')),
    u'Ц': unichr(225),
    u'Ч': unichr(171),
    u'Ш': unichr(172),
    u'Щ': unichr(226),
    u'Ъ': unichr(173),
    u'Ы': unichr(174),
    u'Ь': unichr(ord('b')),
    u'Э': unichr(175),
    u'Ю': unichr(176),
    u'Я': unichr(177),
    u'а': unichr(ord('a')),
    u'б': unichr(178),
    u'в': unichr(179),
    u'г': unichr(180),
    u'д': unichr(227),
    u'е': unichr(ord('e')),
    u'ё': unichr(181),
    u'ж': unichr(182),
    u'з': unichr(183),
    u'и': unichr(184),
    u'й': unichr(185),
    u'к': unichr(186),
    u'л': unichr(187),
    u'м': unichr(188),
    u'н': unichr(188),
    u'о': unichr(ord('o')),
    u'п': unichr(189),
    u'р': unichr(ord('p')),
    u'с': unichr(ord('c')),
    u'т': unichr(191),
    u'у': unichr(ord('y')),
    u'ф': unichr(228),
    u'х': unichr(ord('x')),
    u'ц': unichr(229),
    u'ч': unichr(192),
    u'ш': unichr(193),
    u'щ': unichr(230),
    u'ъ': unichr(194),
    u'ы': unichr(195),
    u'ь': unichr(196),
    u'э': unichr(197),
    u'ю': unichr(198),
    u'я': unichr(199),
}


def from_cyrillic(cyrillic_string):
    result = u''
    for crl_char in cyrillic_string:
        if crl_char in cyrillic_dict:
            result += cyrillic_dict[crl_char]
        else:
            result += crl_char
    return result
